import Wall from "renderer/lib/world/Model/Wall";
import { BackgroundTypes, RoomMap } from "renderer/types";
import Portal from "renderer/lib/world/Model/Portal";
import Switch from "renderer/lib/world/Model/Switch";
import Stash from "renderer/lib/world/Model/Stash";

const map: RoomMap = {
  meta: {
    name: "Hideout",
  },
  backgrounds: [
    [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
    [
      null,
      BackgroundTypes.wood,
      BackgroundTypes.wood,
      BackgroundTypes.wood,
      BackgroundTypes.wood,
      BackgroundTypes.wood,
      BackgroundTypes.wood,
      BackgroundTypes.wood,
      BackgroundTypes.wood,
      BackgroundTypes.wood,
      BackgroundTypes.wood,
      BackgroundTypes.wood,
      BackgroundTypes.wood,
      BackgroundTypes.wood,
      null,
    ],
    [
      null,
      BackgroundTypes.wood,
      BackgroundTypes.wood,
      BackgroundTypes.wood,
      BackgroundTypes.wood,
      BackgroundTypes.wood,
      BackgroundTypes.wood,
      BackgroundTypes.wood,
      BackgroundTypes.wood,
      BackgroundTypes.wood,
      BackgroundTypes.wood,
      BackgroundTypes.wood,
      BackgroundTypes.wood,
      BackgroundTypes.wood,
      null,
    ],
    [
      null,
      BackgroundTypes.wood,
      BackgroundTypes.wood,
      BackgroundTypes.wood,
      BackgroundTypes.wood,
      BackgroundTypes.carpetTopLeft,
      BackgroundTypes.carpetTop,
      BackgroundTypes.carpetTop,
      BackgroundTypes.carpetTop,
      BackgroundTypes.carpetTopRight,
      BackgroundTypes.wood,
      BackgroundTypes.wood,
      BackgroundTypes.wood,
      BackgroundTypes.wood,
      null,
    ],
    [
      null,
      BackgroundTypes.wood,
      BackgroundTypes.wood,
      BackgroundTypes.wood,
      BackgroundTypes.wood,
      BackgroundTypes.carpetLeft,
      BackgroundTypes.carpetCenter,
      BackgroundTypes.carpetCenter,
      BackgroundTypes.carpetCenter,
      BackgroundTypes.carpetRight,
      BackgroundTypes.wood,
      BackgroundTypes.wood,
      BackgroundTypes.wood,
      BackgroundTypes.wood,
      null,
    ],
    [
      null,
      BackgroundTypes.wood,
      BackgroundTypes.wood,
      BackgroundTypes.wood,
      BackgroundTypes.wood,
      BackgroundTypes.carpetBottomLeft,
      BackgroundTypes.carpetBottom,
      BackgroundTypes.carpetBottom,
      BackgroundTypes.carpetBottom,
      BackgroundTypes.carpetBottomRight,
      BackgroundTypes.wood,
      BackgroundTypes.wood,
      BackgroundTypes.wood,
      BackgroundTypes.wood,
      null,
    ],
    [
      null,
      BackgroundTypes.wood,
      BackgroundTypes.wood,
      BackgroundTypes.wood,
      BackgroundTypes.wood,
      BackgroundTypes.wood,
      BackgroundTypes.wood,
      BackgroundTypes.wood,
      BackgroundTypes.wood,
      BackgroundTypes.wood,
      BackgroundTypes.wood,
      BackgroundTypes.wood,
      BackgroundTypes.wood,
      BackgroundTypes.wood,
      null,
    ],
    [
      null,
      BackgroundTypes.wood,
      BackgroundTypes.wood,
      BackgroundTypes.wood,
      BackgroundTypes.wood,
      BackgroundTypes.wood,
      BackgroundTypes.wood,
      BackgroundTypes.wood,
      BackgroundTypes.wood,
      BackgroundTypes.wood,
      BackgroundTypes.wood,
      BackgroundTypes.wood,
      BackgroundTypes.wood,
      BackgroundTypes.wood,
      null,
    ],
    [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
  ],
  models: [
    [Wall, Wall, Wall, Wall, Wall, Wall, Wall, Wall, Wall, Wall, Wall, Wall, Wall, Wall, Wall],
    [Wall, null, null, null, null, null, null, null, null, null, null, null, null, null, Wall],
    [Wall, null, null, null, null, null, null, null, null, null, null, null, Portal, null, Wall],
    [Wall, null, null, null, null, null, null, null, null, null, null, null, null, null, Wall],
    [Wall, null, Stash, null, null, null, null, null, null, null, null, null, Switch, null, Wall],
    [Wall, null, null, null, null, null, null, null, null, null, null, null, null, null, Wall],
    [Wall, null, null, null, null, null, null, null, null, null, null, null, null, null, Wall],
    [Wall, null, null, null, null, null, null, null, null, null, null, null, null, null, Wall],
    [Wall, Wall, Wall, Wall, Wall, Wall, Wall, Wall, Wall, Wall, Wall, Wall, Wall, Wall, Wall],
  ],
  entities: [
    [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
    [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
    [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
    [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
    [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
    [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
    [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
    [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
    [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
  ],
};

export default map;
