import Wall from "renderer/lib/world/Model/Wall";
import Rock from "renderer/lib/world/Model/Rock";
import { BackgroundTypes, RoomMap } from "renderer/types";
import Bat from "renderer/lib/world/Entity/Bat";
import Portal from "renderer/lib/world/Model/Portal";

const map: RoomMap = {
  meta: {
    name: "roomMap2",
  },
  backgrounds: [
    [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
    [
      null,
      BackgroundTypes.wood,
      BackgroundTypes.wood,
      BackgroundTypes.wood,
      BackgroundTypes.wood,
      BackgroundTypes.wood,
      BackgroundTypes.wood,
      BackgroundTypes.wood,
      BackgroundTypes.wood,
      BackgroundTypes.wood,
      BackgroundTypes.wood,
      BackgroundTypes.wood,
      BackgroundTypes.wood,
      BackgroundTypes.wood,
      null,
    ],
    [
      null,
      BackgroundTypes.wood,
      BackgroundTypes.wood,
      BackgroundTypes.wood,
      BackgroundTypes.wood,
      BackgroundTypes.wood,
      BackgroundTypes.wood,
      BackgroundTypes.wood,
      BackgroundTypes.wood,
      BackgroundTypes.wood,
      BackgroundTypes.wood,
      BackgroundTypes.wood,
      BackgroundTypes.wood,
      BackgroundTypes.wood,
      null,
    ],
    [
      null,
      BackgroundTypes.wood,
      BackgroundTypes.wood,
      BackgroundTypes.wood,
      BackgroundTypes.wood,
      BackgroundTypes.carpetTopLeft,
      BackgroundTypes.carpetTop,
      BackgroundTypes.carpetTop,
      BackgroundTypes.carpetTop,
      BackgroundTypes.carpetTopRight,
      BackgroundTypes.wood,
      BackgroundTypes.wood,
      BackgroundTypes.wood,
      BackgroundTypes.wood,
      null,
    ],
    [
      null,
      BackgroundTypes.wood,
      BackgroundTypes.wood,
      BackgroundTypes.wood,
      BackgroundTypes.wood,
      BackgroundTypes.carpetLeft,
      BackgroundTypes.carpetCenter,
      BackgroundTypes.carpetCenter,
      BackgroundTypes.carpetCenter,
      BackgroundTypes.carpetRight,
      BackgroundTypes.wood,
      BackgroundTypes.wood,
      BackgroundTypes.wood,
      BackgroundTypes.wood,
      null,
    ],
    [
      null,
      BackgroundTypes.wood,
      BackgroundTypes.wood,
      BackgroundTypes.wood,
      BackgroundTypes.wood,
      BackgroundTypes.carpetBottomLeft,
      BackgroundTypes.carpetBottom,
      BackgroundTypes.carpetBottom,
      BackgroundTypes.carpetBottom,
      BackgroundTypes.carpetBottomRight,
      BackgroundTypes.wood,
      BackgroundTypes.wood,
      BackgroundTypes.wood,
      BackgroundTypes.wood,
      null,
    ],
    [
      null,
      BackgroundTypes.wood,
      BackgroundTypes.wood,
      BackgroundTypes.wood,
      BackgroundTypes.wood,
      BackgroundTypes.wood,
      BackgroundTypes.wood,
      BackgroundTypes.wood,
      BackgroundTypes.wood,
      BackgroundTypes.wood,
      BackgroundTypes.wood,
      BackgroundTypes.wood,
      BackgroundTypes.wood,
      BackgroundTypes.wood,
      null,
    ],
    [
      null,
      BackgroundTypes.wood,
      BackgroundTypes.wood,
      BackgroundTypes.wood,
      BackgroundTypes.wood,
      BackgroundTypes.wood,
      BackgroundTypes.wood,
      BackgroundTypes.wood,
      BackgroundTypes.wood,
      BackgroundTypes.wood,
      BackgroundTypes.wood,
      BackgroundTypes.wood,
      BackgroundTypes.wood,
      BackgroundTypes.wood,
      null,
    ],
    [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
  ],
  models: [
    [Wall, Wall, Wall, Wall, Wall, Wall, Wall, Wall, Wall, Wall, Wall, Wall, Wall, Wall, Wall],
    [Wall, null, null, null, null, null, null, null, null, null, null, null, null, null, Wall],
    [Wall, null, null, null, null, null, Rock, Rock, Rock, null, null, null, null, null, Wall],
    [Wall, null, null, null, null, null, Rock, null, null, null, null, null, null, null, Wall],
    [Wall, null, null, null, null, null, Rock, null, null, null, null, null, null, null, Wall],
    [Wall, null, null, null, null, null, Rock, null, null, null, null, null, null, null, Wall],
    [Wall, null, null, null, null, null, Rock, Rock, Rock, null, null, null, null, null, Wall],
    [Wall, null, null, null, null, null, null, null, null, null, null, null, null, null, Wall],
    [Wall, Wall, Wall, Wall, Wall, Wall, Wall, Wall, Wall, Wall, Wall, Wall, Wall, Wall, Wall],
  ],
  entities: [
    [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
    [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
    [null, null, null, null, null, null, null, null, null, null, null, null, Bat, null, null],
    [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
    [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
    [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
    [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
    [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
    [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
  ],
};

export default map;
